name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  test-var:
    description: "Testing a variable"
    value: ${{ steps.vertex-execution.outputs.test-var}}
env:
  GLO-VAR: 'i am a global variable'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      env:
        within-scope: ${{ 'i am a in-scope variable' }}
      #run: echo "::set-output name=random-number::$(echo $RANDOM)" #outputs random variable
      #run: echo "::set-output name=random-number::$(echo $GLO-VAR)" # null output
      #run: echo "::set-output name=random-number::$(echo ${{env.GLO-VAR}})" # null output
      run: echo "::set-output name=random-number::$(echo $'{within-scope}')" # null output
      shell: bash
    - id: vertex-execution
      env:
        hello-there: ${{ 'hello there' }}
      # run: echo "::set-output name=test-var::$(echo $hello-there)" #outputs hello-there
      run: |
        for i in {1..5}
          do
          echo "::set-output name=test-var::$(echo $hello-there)" "${hello-there}"
        done
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - run: goodbye.sh
      shell: bash